<a href="https://colab.research.google.com/github/Remonah-3/matrix_multiplication_assignment/blob/main/Assignment_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

A = np.array([[-1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])

B = np.array([[0, 2, 1],
              [0, 2, -8],
              [2, 9, -1]])

print("Matrix A")
print(A)
print("Matrix B")
print(B)

Matrix A
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
Matrix B
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


In [12]:
C1 = np.matmul(A, B)
print("A x B using np.matmul")
print(C1)
C2 = np.dot(A, B)
print("A x B using np.dot")
print(C2)
C3 = A @ B
print("A x B using @ operator")
print(C3)

A x B using np.matmul
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
A x B using np.dot
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
A x B using @ operator
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [13]:
def matmul_scratch(a, b):
    result = np.zeros((a.shape[0], b.shape[1]))

    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                result[i, j] += a[i, k] * b[k, j]
    return result

C_scratch = matmul_scratch(A, B)
print("A x B using scratch method")
print(C_scratch)

A x B using scratch method
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [14]:
def multiplicable(a, b):
    if a.shape[1] != b.shape[0]:
        print("Cannot multiply: number of columns in A != number of rows in B")
        return False
    return True

D = np.array([[-1, 2, 3],
              [4, -5, 6]])

E = np.array([[-9, 8, 7],
              [6, -5, 4]])

if multiplicable(D, E):
    print(np.matmul(D, E))

Cannot multiply: number of columns in A != number of rows in B


In [15]:
E_transposed = E.T

result_transpose = np.matmul(D, E_transposed)
print("D x E_transposed")
print(result_transpose)

D x E_transposed
[[ 46  -4]
 [-34  73]]
